# Generated by Django 4.2.7 on 2023-11-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Managet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pseudo', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
