# Generated by Django 4.2.7 on 2023-12-08 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attente',
            name='birth_date',
        ),
    ]
