# Generated by Django 4.2.7 on 2023-11-30 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Managet',
            new_name='Manager',
        ),
    ]
