# Generated by Django 4.2.7 on 2023-11-30 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0003_hospital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='adress',
            new_name='address',
        ),
    ]
