# Generated by Django 4.2.7 on 2023-11-30 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0004_rename_adress_hospital_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidapp.manager')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidapp.hospital')),
            ],
        ),
    ]
