# Generated by Django 4.2.7 on 2023-12-01 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0005_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('symptoms', models.TextField()),
                ('medications', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('disease_histoty', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidapp.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidapp.hospital')),
            ],
        ),
    ]
