# Generated by Django 4.2.7 on 2023-12-01 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0006_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='disease_histoty',
            new_name='disease_history',
        ),
    ]
