# Generated by Django 4.2.7 on 2023-12-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0007_rename_disease_histoty_patient_disease_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
